name: puzzle_3_3_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.2
  equatable: ^2.0.3
  google_fonts: ^2.2.0
  shared_preferences: ^2.0.12
  get_it: ^7.2.0
  audio_session: ^0.1.6+1
  just_audio: ^0.9.18
  image: ^3.1.1
  smooth_page_indicator: ^1.0.0+2
  url_strategy: ^0.2.0
  rive: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/images/jungle.png
    - assets/images/dash.png
    - assets/images/hero-dash.png
    - assets/images/relax-dash.png
    - assets/images/numeric-puzzle.png
    - assets/rive/winner.riv
    - assets/sounds/
    - assets/animals/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PuzzleIcons
      fonts:
        - asset: assets/icons/PuzzleIcons.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/src/l10n

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/icon.png"
